version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "2000:80"
    links:
      - app

  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    links: 
      - database
      - elasticsearch
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  database:
    image: mysql:5.6
    environment:
        - "MYSQL_ROOT_PASSWORD=secret"
        - "MYSQL_DATABASE=laravel-for-test"
    ports:
        - "33020:3306"

  elasticsearch:
    image: elasticsearch
    ports:
        - "9200:9200"

